import type { FnSpec } from '../types.ts';

const d = (name: string, signature: string, summary: string, cases: FnSpec['cases'], extra: Partial<FnSpec> = {}): FnSpec => ({
  name,
  category: 'statistical',
  signature,
  summary,
  cases,
  ...extra,
});

/** Probability distributions and the gamma function (statistical category). */
export const distributions: FnSpec[] = [
  d('NORM.DIST', 'NORM.DIST(x, mean, standard_dev, cumulative)', 'Returns the normal distribution (cumulative or density) for a mean and standard deviation.', [
    '=NORM.DIST(42, 40, 1.5, TRUE)', '=NORM.DIST(42, 40, 1.5, FALSE)', '=NORM.DIST(40, 40, 1.5, TRUE)', '=NORM.DIST(-1, 0, 1, TRUE)',
    '=NORM.DIST(10, 0, 1, FALSE)',
    { f: '=NORM.DIST(-8, 0, 1, TRUE)', expect: 6.2209605742717841e-16, why: 'formula.js loses precision in the lower tail' },
    '=NORM.DIST(1, 0, 0, TRUE)', '=NORM.DIST(1, 0, -1, FALSE)', '=NORM.DIST("x", 0, 1, TRUE)',
  ]),
  d('NORM.INV', 'NORM.INV(probability, mean, standard_dev)', 'Returns the inverse of the normal cumulative distribution for a mean and standard deviation.', [
    '=NORM.INV(0.908789, 40, 1.5)', '=NORM.INV(0.5, 10, 2)', '=NORM.INV(0.01, 0, 1)', '=NORM.INV(0.999, 5, 3)',
    { f: '=NORM.INV(0, 0, 1)', expect: { error: '#NUM!' }, why: 'probability must be in (0, 1)' },
    { f: '=NORM.INV(1, 0, 1)', expect: { error: '#NUM!' }, why: 'probability must be in (0, 1)' },
    { f: '=NORM.INV(0.5, 0, 0)', expect: { error: '#NUM!' }, why: 'standard_dev must be > 0' },
    '=NORM.INV("x", 0, 1)',
  ]),
  d('NORM.S.DIST', 'NORM.S.DIST(z, cumulative)', 'Returns the standard normal distribution (cumulative or density).', [
    '=NORM.S.DIST(1.333333, TRUE)', '=NORM.S.DIST(1.333333, FALSE)', '=NORM.S.DIST(0, TRUE)', '=NORM.S.DIST(0, FALSE)', '=NORM.S.DIST(-2, TRUE)',
    { f: '=NORM.S.DIST(-10, TRUE)', expect: 7.6198530241605261e-24, why: 'formula.js underflows to 0 in the lower tail' },
    '=NORM.S.DIST(5, TRUE)', '=NORM.S.DIST("x", TRUE)',
  ]),
  d('NORM.S.INV', 'NORM.S.INV(probability)', 'Returns the inverse of the standard normal cumulative distribution.', [
    '=NORM.S.INV(0.908789)',
    { f: '=NORM.S.INV(0.5)', expect: 0, why: 'the median of the standard normal is exactly 0' },
    '=NORM.S.INV(0.025)', '=NORM.S.INV(0.975)',
    { f: '=NORM.S.INV(1E-10)', expect: -6.3613409024040562, why: 'formula.js is inaccurate here; value from a 40-digit computation' },
    { f: '=NORM.S.INV(0)', expect: { error: '#NUM!' }, why: 'probability must be in (0, 1)' },
    { f: '=NORM.S.INV(1.5)', expect: { error: '#NUM!' }, why: 'probability must be in (0, 1)' },
    '=NORM.S.INV("x")',
  ]),
  d('LOGNORM.DIST', 'LOGNORM.DIST(x, mean, standard_dev, cumulative)', 'Returns the lognormal distribution of x, where ln(x) is normal with the given mean and standard deviation.', [
    '=LOGNORM.DIST(4, 3.5, 1.2, TRUE)', '=LOGNORM.DIST(4, 3.5, 1.2, FALSE)', '=LOGNORM.DIST(1, 0, 1, TRUE)', '=LOGNORM.DIST(2, 0, 0.5, FALSE)',
    { f: '=LOGNORM.DIST(0, 0, 1, TRUE)', expect: { error: '#NUM!' }, why: 'x must be > 0' },
    '=LOGNORM.DIST(1, 0, 0, TRUE)', '=LOGNORM.DIST("x", 0, 1, TRUE)',
  ]),
  d('CONFIDENCE.NORM', 'CONFIDENCE.NORM(alpha, standard_dev, size)', 'Returns the half-width of a normal confidence interval for a population mean (size is truncated).', [
    '=CONFIDENCE.NORM(0.05, 2.5, 50)', '=CONFIDENCE.NORM(0.1, 1, 10)', '=CONFIDENCE.NORM(0.01, 3, 100)',
    { f: '=CONFIDENCE.NORM(0.05, 2.5, 50.9)', expect: 0.69295191217483897, why: 'size is truncated to 50' },
    { f: '=CONFIDENCE.NORM(0, 1, 10)', expect: { error: '#NUM!' }, why: 'alpha must be in (0, 1)' },
    { f: '=CONFIDENCE.NORM(0.05, 0, 10)', expect: { error: '#NUM!' }, why: 'standard_dev must be > 0' },
    { f: '=CONFIDENCE.NORM(0.05, 1, 0.5)', expect: { error: '#NUM!' }, why: 'size must be >= 1' },
    '=CONFIDENCE.NORM("x", 1, 10)',
  ]),
  d('EXPON.DIST', 'EXPON.DIST(x, lambda, cumulative)', 'Returns the exponential distribution (cumulative or density) with rate lambda.', [
    '=EXPON.DIST(0.2, 10, TRUE)', '=EXPON.DIST(0.2, 10, FALSE)', '=EXPON.DIST(0, 3, TRUE)', '=EXPON.DIST(0, 3, FALSE)', '=EXPON.DIST(2, 0.5, TRUE)',
    { f: '=EXPON.DIST(-1, 1, TRUE)', expect: { error: '#NUM!' }, why: 'x must be >= 0' },
    { f: '=EXPON.DIST(1, 0, TRUE)', expect: { error: '#NUM!' }, why: 'lambda must be > 0' },
    '=EXPON.DIST("x", 1, TRUE)',
  ]),
  d('POISSON.DIST', 'POISSON.DIST(x, mean, cumulative)', 'Returns the Poisson distribution (cumulative or mass) of x events (truncated) for a mean.', [
    '=POISSON.DIST(2, 5, FALSE)', '=POISSON.DIST(2, 5, TRUE)', '=POISSON.DIST(0, 0, FALSE)', '=POISSON.DIST(10, 3.5, FALSE)',
    { f: '=POISSON.DIST(2.9, 5, FALSE)', expect: 0.084224337488568339, why: 'x is truncated to 2' },
    '=POISSON.DIST(20, 15, TRUE)',
    { f: '=POISSON.DIST(-1, 5, TRUE)', expect: { error: '#NUM!' }, why: 'x must be >= 0' },
    { f: '=POISSON.DIST(2, -1, TRUE)', expect: { error: '#NUM!' }, why: 'mean must be >= 0' },
    '=POISSON.DIST("x", 5, TRUE)',
  ]),
  d('BINOM.DIST', 'BINOM.DIST(number_s, trials, probability_s, cumulative)', 'Returns the binomial distribution (cumulative or mass) of number_s successes in trials (both truncated).', [
    '=BINOM.DIST(6, 10, 0.5, FALSE)', '=BINOM.DIST(6, 10, 0.5, TRUE)', '=BINOM.DIST(0, 5, 0.2, FALSE)',
    { f: '=BINOM.DIST(3, 20, 0.1, TRUE)', expect: 0.86704667656566492, why: 'formula.js result is rounded to 10 digits' },
    { f: '=BINOM.DIST(6.9, 10.2, 0.5, FALSE)', expect: 0.205078125, why: 'number_s and trials are truncated (6 of 10)' },
    '=BINOM.DIST(5, 5, 1, FALSE)', '=BINOM.DIST(11, 10, 0.5, FALSE)',
    { f: '=BINOM.DIST(-1, 10, 0.5, TRUE)', expect: { error: '#NUM!' }, why: 'number_s must be >= 0' },
    '=BINOM.DIST(2, 10, 1.5, TRUE)', '=BINOM.DIST("x", 10, 0.5, TRUE)',
  ]),
  d('WEIBULL.DIST', 'WEIBULL.DIST(x, alpha, beta, cumulative)', 'Returns the Weibull distribution (cumulative or density) with shape alpha and scale beta.', [
    '=WEIBULL.DIST(105, 20, 100, TRUE)', '=WEIBULL.DIST(105, 20, 100, FALSE)', '=WEIBULL.DIST(1, 1, 1, TRUE)', '=WEIBULL.DIST(2, 0.5, 3, FALSE)',
    '=WEIBULL.DIST(0, 2, 1, TRUE)',
    { f: '=WEIBULL.DIST(-1, 2, 1, TRUE)', expect: { error: '#NUM!' }, why: 'x must be >= 0' },
    { f: '=WEIBULL.DIST(1, 0, 1, TRUE)', expect: { error: '#NUM!' }, why: 'alpha must be > 0' },
    '=WEIBULL.DIST("x", 2, 1, TRUE)',
  ]),
  d('GAMMA', 'GAMMA(number)', 'Returns the gamma function value; #NUM! at 0 and the negative integers.', [
    { f: '=GAMMA(2.5)', expect: 1.329340388179137, why: 'formula.js is inaccurate here; value from a 40-digit computation' },
    '=GAMMA(5)',
    { f: '=GAMMA(0.5)', expect: 1.772453850905516, why: 'sqrt(pi); formula.js is inaccurate' },
    { f: '=GAMMA(-0.75)', expect: -4.8341465442958777, why: 'formula.js is inaccurate here; value from a 40-digit computation' },
    '=GAMMA(1)', '=GAMMA(0)', '=GAMMA(-2)', '=GAMMA(172)', '=GAMMA("x")',
  ]),
  d('GAMMALN', 'GAMMALN(x)', 'Returns the natural logarithm of the gamma function for x > 0.', [
    '=GAMMALN(4)', '=GAMMALN(0.5)', '=GAMMALN(1)', '=GAMMALN(100)', '=GAMMALN(0.001)', '=GAMMALN(0)',
    { f: '=GAMMALN(-1.5)', expect: { error: '#NUM!' }, why: 'x must be > 0' },
    '=GAMMALN("x")',
  ]),
  d('GAMMA.DIST', 'GAMMA.DIST(x, alpha, beta, cumulative)', 'Returns the gamma distribution (cumulative or density) with shape alpha and scale beta.', [
    '=GAMMA.DIST(10.00001131, 9, 2, TRUE)', '=GAMMA.DIST(10.00001131, 9, 2, FALSE)', '=GAMMA.DIST(1, 1, 1, TRUE)', '=GAMMA.DIST(2, 0.5, 1, FALSE)',
    '=GAMMA.DIST(30, 3, 2, TRUE)', '=GAMMA.DIST(0, 2, 1, TRUE)',
    { f: '=GAMMA.DIST(-1, 2, 1, TRUE)', expect: { error: '#NUM!' }, why: 'x must be >= 0' },
    { f: '=GAMMA.DIST(1, 0, 1, TRUE)', expect: { error: '#NUM!' }, why: 'alpha must be > 0' },
    { f: '=GAMMA.DIST(1, 2, 0, TRUE)', expect: { error: '#NUM!' }, why: 'beta must be > 0' },
    '=GAMMA.DIST("x", 2, 1, TRUE)',
  ]),
  d('CHISQ.DIST', 'CHISQ.DIST(x, deg_freedom, cumulative)', 'Returns the left-tailed chi-squared distribution (cumulative or density); deg_freedom is truncated.', [
    '=CHISQ.DIST(0.5, 1, TRUE)', '=CHISQ.DIST(2, 3, FALSE)', '=CHISQ.DIST(3.84, 1, TRUE)', '=CHISQ.DIST(10, 4, TRUE)',
    { f: '=CHISQ.DIST(2, 3.9, FALSE)', expect: 0.20755374871029735, why: 'deg_freedom is truncated to 3' },
    '=CHISQ.DIST(0, 2, TRUE)',
    { f: '=CHISQ.DIST(-1, 2, TRUE)', expect: { error: '#NUM!' }, why: 'x must be >= 0' },
    '=CHISQ.DIST(1, 0, TRUE)', '=CHISQ.DIST("x", 2, TRUE)',
  ]),
  d('BETA.DIST', 'BETA.DIST(x, alpha, beta, cumulative, [A], [B])', 'Returns the beta distribution (cumulative or density) on the interval [A, B] (0 and 1 by default).', [
    { f: '=BETA.DIST(2, 8, 10, TRUE, 1, 3)', expect: 0.6854705810546875, why: 'exact value I(0.5; 8, 10); formula.js is slightly off' },
    { f: '=BETA.DIST(2, 8, 10, FALSE, 1, 3)', expect: 1.4837646484375, why: 'the density is scaled by 1 / (B - A); formula.js does not' },
    '=BETA.DIST(0.4, 2, 3, TRUE)', '=BETA.DIST(0.4, 2, 3, FALSE)', '=BETA.DIST(0.5, 1, 1, TRUE)',
    { f: '=BETA.DIST(0.9, 0.5, 0.5, TRUE)', expect: 0.79516723530086655, why: 'formula.js is inaccurate here; value from a 40-digit computation' },
    { f: '=BETA.DIST(1.5, 2, 3, TRUE)', expect: { error: '#NUM!' }, why: 'x must lie in [A, B]' },
    { f: '=BETA.DIST(0.5, 0, 3, TRUE)', expect: { error: '#NUM!' }, why: 'alpha must be > 0' },
    '=BETA.DIST(2, 2, 3, TRUE, 2, 2)', '=BETA.DIST("x", 2, 3, TRUE)',
  ]),
  d('T.DIST', 'T.DIST(x, deg_freedom, cumulative)', 'Returns the left-tailed Student t-distribution (cumulative or density); deg_freedom is truncated.', [
    { f: '=T.DIST(60, 1, TRUE)', expect: 0.99469532636737673, why: 'formula.js T.DIST is broken' },
    { f: '=T.DIST(8, 3, FALSE)', expect: 0.00073690652094692633, why: 'formula.js T.DIST is broken' },
    { f: '=T.DIST(0, 5, TRUE)', expect: 0.5, why: 'formula.js T.DIST is broken' },
    { f: '=T.DIST(-1.5, 10, TRUE)', expect: 0.08225366322272009, why: 'formula.js T.DIST is broken' },
    { f: '=T.DIST(2, 30, FALSE)', expect: 0.056852275047197964, why: 'formula.js T.DIST is broken' },
    { f: '=T.DIST(1, 2, TRUE)', expect: 0.78867513459481288, why: 'formula.js T.DIST is broken' },
    { f: '=T.DIST(-3, 4, FALSE)', expect: 0.019693498090836537, why: 'formula.js T.DIST is broken' },
    '=T.DIST(1, 0, TRUE)',
    { f: '=T.DIST("x", 5, TRUE)', expect: { error: '#VALUE!' }, why: 'non-numeric x' },
  ]),
  d('F.DIST', 'F.DIST(x, deg_freedom1, deg_freedom2, cumulative)', 'Returns the left-tailed F probability distribution (cumulative or density); degrees of freedom are truncated.', [
    '=F.DIST(15.2069, 6, 4, TRUE)', '=F.DIST(15.2069, 6, 4, FALSE)',
    { f: '=F.DIST(1, 1, 1, TRUE)', expect: 0.5, why: 'F(1; 1, 1) is exactly 0.5; formula.js is inaccurate' },
    '=F.DIST(2.5, 5, 10, FALSE)',
    { f: '=F.DIST(0.5, 3.9, 8, TRUE)', expect: 0.30737513305615365, why: 'deg_freedom1 is truncated to 3' },
    { f: '=F.DIST(-1, 2, 3, TRUE)', expect: { error: '#NUM!' }, why: 'x must be >= 0' },
    '=F.DIST(1, 0, 3, TRUE)', '=F.DIST("x", 2, 3, TRUE)',
  ]),
];
