import type { FnSpec } from '../types.ts';

const m = (name: string, signature: string, summary: string, cases: FnSpec['cases'], extra: Partial<FnSpec> = {}): FnSpec => ({
  name,
  category: 'math',
  signature,
  summary,
  cases,
  ...extra,
});

export const math: FnSpec[] = [
  m('ABS', 'ABS(number)', 'Returns the absolute value of a number.', ['=ABS(-4.5)', '=ABS(3)', '=ABS(0)', '=ABS("-2")', '=ABS(TRUE)', { f: '=ABS("abc")', expect: { error: '#VALUE!' }, why: 'formula.js returns #VALUE! too; listed for clarity' }]),
  m('ACOS', 'ACOS(number)', 'Returns the arccosine (in radians) of a number between -1 and 1.', ['=ACOS(-0.5)', '=ACOS(1)', '=ACOS(0)', '=ACOS(0.25)', '=ACOS(2)', '=ACOS("x")']),
  m('ACOSH', 'ACOSH(number)', 'Returns the inverse hyperbolic cosine of a number >= 1.', ['=ACOSH(1)', '=ACOSH(10)', '=ACOSH(2.5)', { f: '=ACOSH(0.5)', expect: { error: '#NUM!' }, why: 'Excel returns #NUM! below 1' }, '=ACOSH("x")']),
  m('ACOT', 'ACOT(number)', 'Returns the principal arccotangent of a number, in (0, pi).', ['=ACOT(2)', '=ACOT(1)', { f: '=ACOT(0)', expect: 1.5707963267948966, why: 'ACOT(0) is pi/2' }, { f: '=ACOT(-1)', expect: 2.356194490192345, why: 'Excel returns a value in (0, pi): 3*pi/4' }, '=ACOT("x")']),
  m('ACOTH', 'ACOTH(number)', 'Returns the inverse hyperbolic cotangent of a number with absolute value > 1.', ['=ACOTH(6)', '=ACOTH(-2)', '=ACOTH(1.5)', { f: '=ACOTH(0.5)', expect: { error: '#NUM!' }, why: 'Excel returns #NUM! for |x| <= 1' }, '=ACOTH("x")']),
  m('ARABIC', 'ARABIC(text)', 'Converts a roman numeral to a number.', ['=ARABIC("MCMXCIX")', { f: '=ARABIC("mmxxiv")', expect: 2024, why: 'ARABIC is case-insensitive' }, '=ARABIC("IV")', '=ARABIC("")', { f: '=ARABIC("-XL")', expect: -40, why: 'Excel accepts a leading minus sign' }, { f: '=ARABIC("ABC")', expect: { error: '#VALUE!' }, why: 'invalid numeral' }]),
  m('ASIN', 'ASIN(number)', 'Returns the arcsine (in radians) of a number between -1 and 1.', ['=ASIN(-0.5)', '=ASIN(1)', '=ASIN(0)', '=ASIN(0.3)', '=ASIN(-1.5)', '=ASIN("x")']),
  m('ASINH', 'ASINH(number)', 'Returns the inverse hyperbolic sine of a number.', ['=ASINH(-2.5)', '=ASINH(10)', '=ASINH(0)', '=ASINH(1)', '=ASINH("x")']),
  m('ATAN', 'ATAN(number)', 'Returns the arctangent (in radians) of a number.', ['=ATAN(1)', '=ATAN(-2)', '=ATAN(0)', '=ATAN(1000)', '=ATAN("x")']),
  m('ATAN2', 'ATAN2(x_num, y_num)', 'Returns the arctangent of the point (x_num, y_num), in (-pi, pi].', ['=ATAN2(1, 1)', '=ATAN2(-1, -1)', { f: '=ATAN2(-1, 0)', expect: 3.141592653589793, why: 'formula.js swaps x and y; the point (-1, 0) has angle pi' }, { f: '=ATAN2(0, 2)', expect: 1.5707963267948966, why: 'formula.js swaps x and y; the point (0, 2) has angle pi/2' }, { f: '=ATAN2(0, 0)', expect: { error: '#DIV/0!' }, why: 'both coordinates zero' }, '=ATAN2("x", 1)']),
  m('ATANH', 'ATANH(number)', 'Returns the inverse hyperbolic tangent of a number strictly between -1 and 1.', ['=ATANH(0.76159416)', '=ATANH(-0.1)', '=ATANH(0)', '=ATANH(1)', '=ATANH("x")']),
  m('CEILING', 'CEILING(number, significance)', 'Rounds a number up (away from zero for negative significance) to the nearest multiple of significance.', [
    '=CEILING(2.5, 1)', '=CEILING(-2.5, -2)', '=CEILING(1.5, 0.1)', '=CEILING(0.234, 0.01)',
    { f: '=CEILING(-2.5, 2)', expect: -2, why: 'Excel 2010+: a negative number with positive significance rounds toward zero' },
    { f: '=CEILING(2.5, -2)', expect: { error: '#NUM!' }, why: 'positive number with negative significance' },
    '=CEILING(0, 3)', { f: '=CEILING(5, 0)', expect: 0, why: 'significance 0 gives 0' },
  ]),
  m('CEILING.MATH', 'CEILING.MATH(number, [significance], [mode])', 'Rounds a number up to the nearest integer or multiple of significance; mode controls negative numbers.', [
    '=CEILING.MATH(24.3, 5)', '=CEILING.MATH(6.7)', '=CEILING.MATH(-8.1, 2)', '=CEILING.MATH(-5.5, 2, -1)', '=CEILING.MATH(-5.5, 2, 0)', '=CEILING.MATH(5.5, -2)', '=CEILING.MATH(0, 4)', '=CEILING.MATH("x")',
  ]),
  m('COMBIN', 'COMBIN(number, number_chosen)', 'Returns the number of combinations of number_chosen items from number items.', ['=COMBIN(8, 2)', '=COMBIN(10, 0)', '=COMBIN(52, 5)', '=COMBIN(8.9, 2.7)', '=COMBIN(2, 3)', '=COMBIN(-1, 0)', '=COMBIN("x", 1)']),
  m('COMBINA', 'COMBINA(number, number_chosen)', 'Returns the number of combinations with repetitions.', ['=COMBINA(4, 3)', '=COMBINA(10, 3)', '=COMBINA(0, 0)', '=COMBINA(3, 0)', '=COMBINA(-1, 2)', '=COMBINA("x", 1)']),
  m('COS', 'COS(number)', 'Returns the cosine of an angle in radians.', ['=COS(1.047)', '=COS(0)', '=COS(PI())', '=COS(-2)', '=COS("x")']),
  m('COSH', 'COSH(number)', 'Returns the hyperbolic cosine of a number.', ['=COSH(4)', '=COSH(0)', '=COSH(-1.5)', { f: '=COSH(1000)', expect: { error: '#NUM!' }, why: 'overflow' }, '=COSH("x")']),
  m('COT', 'COT(number)', 'Returns the cotangent of an angle in radians.', ['=COT(30)', '=COT(1)', '=COT(-0.5)', '=COT(0)', '=COT("x")']),
  m('COTH', 'COTH(number)', 'Returns the hyperbolic cotangent of a number.', ['=COTH(2)', '=COTH(-0.5)', '=COTH(10)', '=COTH(0)', '=COTH("x")']),
  m('CSC', 'CSC(number)', 'Returns the cosecant of an angle in radians.', ['=CSC(15)', '=CSC(1)', '=CSC(-2)', '=CSC(0)', '=CSC("x")']),
  m('CSCH', 'CSCH(number)', 'Returns the hyperbolic cosecant of a number.', ['=CSCH(1.5)', '=CSCH(-1)', '=CSCH(5)', '=CSCH(0)', '=CSCH("x")']),
  m('DEGREES', 'DEGREES(angle)', 'Converts radians to degrees.', ['=DEGREES(PI())', '=DEGREES(1)', '=DEGREES(-0.5)', '=DEGREES(0)', '=DEGREES("x")']),
  m('EVEN', 'EVEN(number)', 'Rounds a number away from zero to the nearest even integer.', ['=EVEN(1.5)', '=EVEN(3)', '=EVEN(2)', '=EVEN(-1)', '=EVEN(0)', '=EVEN(-2.5)', '=EVEN("x")']),
  m('EXP', 'EXP(number)', 'Returns e raised to the power of a number.', ['=EXP(1)', '=EXP(2)', '=EXP(0)', '=EXP(-1.5)', { f: '=EXP(1000)', expect: { error: '#NUM!' }, why: 'overflow' }, '=EXP("x")']),
  m('FACT', 'FACT(number)', 'Returns the factorial of a number (truncated to an integer).', ['=FACT(5)', '=FACT(1.9)', '=FACT(0)', '=FACT(20)', { f: '=FACT(-1)', expect: { error: '#NUM!' }, why: 'negative numbers give #NUM!' }, { f: '=FACT(171)', expect: { error: '#NUM!' }, why: 'overflow' }, '=FACT("x")']),
  m('FACTDOUBLE', 'FACTDOUBLE(number)', 'Returns the double factorial of a number (truncated to an integer).', ['=FACTDOUBLE(6)', '=FACTDOUBLE(7)', '=FACTDOUBLE(0)', '=FACTDOUBLE(7.9)', { f: '=FACTDOUBLE(-1)', expect: 1, why: 'Excel defines FACTDOUBLE(-1) as 1' }, { f: '=FACTDOUBLE(-2)', expect: { error: '#NUM!' }, why: 'negative below -1' }, '=FACTDOUBLE("x")']),
  m('FLOOR', 'FLOOR(number, significance)', 'Rounds a number down (toward zero for negative significance) to the nearest multiple of significance.', [
    '=FLOOR(3.7, 2)', '=FLOOR(-2.5, -2)', '=FLOOR(1.58, 0.1)', '=FLOOR(0.234, 0.01)',
    { f: '=FLOOR(-2.5, 2)', expect: -4, why: 'Excel 2010+: a negative number with positive significance rounds away from zero' },
    { f: '=FLOOR(2.5, -2)', expect: { error: '#NUM!' }, why: 'positive number with negative significance' },
    { f: '=FLOOR(5, 0)', expect: { error: '#DIV/0!' }, why: 'significance 0' },
    '=FLOOR("x", 1)',
  ]),
  m('FLOOR.MATH', 'FLOOR.MATH(number, [significance], [mode])', 'Rounds a number down to the nearest integer or multiple of significance; mode controls negative numbers.', [
    '=FLOOR.MATH(24.3, 5)', '=FLOOR.MATH(6.7)', '=FLOOR.MATH(-8.1, 2)', '=FLOOR.MATH(-5.5, 2, -1)', '=FLOOR.MATH(-5.5, 2)', '=FLOOR.MATH(5.5, -2)', '=FLOOR.MATH(0, 3)', '=FLOOR.MATH("x")',
  ]),
  m('GCD', 'GCD(number1, [number2], ...)', 'Returns the greatest common divisor of integers (arguments are truncated).', ['=GCD(5, 2)', '=GCD(24, 36)', '=GCD(7, 1)', '=GCD(5, 0)', '=GCD({12, 18}, 27)', { f: '=GCD(24.9, 36)', expect: 12, why: 'arguments are truncated to integers' }, { f: '=GCD(-1, 2)', expect: { error: '#NUM!' }, why: 'negative arguments give #NUM!' }, '=GCD("x", 2)']),
  m('INT', 'INT(number)', 'Rounds a number down to the nearest integer.', ['=INT(8.9)', '=INT(-8.9)', '=INT(-0.5)', '=INT(5)', '=INT("2.5")', '=INT("x")']),
  m('LCM', 'LCM(number1, [number2], ...)', 'Returns the least common multiple of integers (arguments are truncated).', ['=LCM(5, 2)', '=LCM(24, 36)', '=LCM(3, 0)', '=LCM({2, 3}, 4)', { f: '=LCM(4.9, 6)', expect: 12, why: 'arguments are truncated to integers' }, { f: '=LCM(-1, 2)', expect: { error: '#NUM!' }, why: 'negative arguments give #NUM!' }, '=LCM("x", 2)']),
  m('LN', 'LN(number)', 'Returns the natural logarithm of a positive number.', ['=LN(86)', '=LN(EXP(3))', '=LN(1)', '=LN(0)', '=LN(-1)', '=LN("x")']),
  m('LOG', 'LOG(number, [base])', 'Returns the logarithm of a number to a base (10 by default).', ['=LOG(10)', '=LOG(8, 2)', '=LOG(86, 2.7182818)', '=LOG(0.5, 4)', '=LOG(0)', { f: '=LOG(10, 1)', expect: { error: '#DIV/0!' }, why: 'base 1 divides by ln(1) = 0' }, '=LOG(10, -2)', '=LOG("x")']),
  m('LOG10', 'LOG10(number)', 'Returns the base-10 logarithm of a positive number.', ['=LOG10(86)', '=LOG10(10)', '=LOG10(100000)', '=LOG10(0.001)', '=LOG10(0)', '=LOG10("x")']),
  m('MOD', 'MOD(number, divisor)', 'Returns the remainder after division; the result has the sign of the divisor.', ['=MOD(3, 2)', '=MOD(-3, 2)', '=MOD(3, -2)', { f: '=MOD(-3, -2)', expect: -1, why: 'result has the sign of the divisor' }, '=MOD(5.5, 2)', '=MOD(0, 5)', '=MOD(3, 0)', '=MOD("x", 2)']),
  m('MROUND', 'MROUND(number, multiple)', 'Rounds a number to the nearest multiple (halves away from zero).', ['=MROUND(10, 3)', '=MROUND(-10, -3)', '=MROUND(1.3, 0.2)', '=MROUND(7.5, 5)', '=MROUND(5, 0)', { f: '=MROUND(5, -2)', expect: { error: '#NUM!' }, why: 'number and multiple must have the same sign' }, '=MROUND("x", 2)']),
  m('MULTINOMIAL', 'MULTINOMIAL(number1, [number2], ...)', 'Returns the ratio of the factorial of a sum to the product of factorials.', ['=MULTINOMIAL(2, 3, 4)', '=MULTINOMIAL(1, 1)', '=MULTINOMIAL(5)', '=MULTINOMIAL({1, 2}, 3)', '=MULTINOMIAL(0, 0)', { f: '=MULTINOMIAL(-1, 2)', expect: { error: '#NUM!' }, why: 'negative numbers give #NUM!' }, '=MULTINOMIAL("x")']),
  m('ODD', 'ODD(number)', 'Rounds a number away from zero to the nearest odd integer.', ['=ODD(1.5)', '=ODD(3)', '=ODD(2)', '=ODD(-1)', '=ODD(-2)', '=ODD(0)', '=ODD("x")']),
  m('PI', 'PI()', 'Returns the number pi.', ['=PI()', '=PI()*2', '=PI()/2', '=-PI()']),
  m('POWER', 'POWER(number, power)', 'Returns a number raised to a power.', ['=POWER(5, 2)', '=POWER(98.6, 3.2)', '=POWER(4, 5/4)', '=POWER(2, -1)', '=POWER(-8, 1/3)', { f: '=POWER(0, 0)', expect: { error: '#NUM!' }, why: 'Excel returns #NUM! for 0^0' }, { f: '=POWER(0, -1)', expect: { error: '#DIV/0!' }, why: '0 to a negative power' }, '=POWER("x", 2)']),
  m('PRODUCT', 'PRODUCT(number1, [number2], ...)', 'Multiplies its arguments (numbers inside arrays; text and booleans in arrays are ignored).', ['=PRODUCT(5, 15, 30)', '=PRODUCT({5, 15, 30}, 2)', '=PRODUCT(2, "3")', { f: '=PRODUCT({2, "x", TRUE}, 3)', expect: 6, why: 'text and booleans inside arrays are ignored' }, '=PRODUCT(-1.5, 2)', { f: '=PRODUCT(2, "x")', expect: { error: '#VALUE!' }, why: 'Excel: direct text that is not a number is #VALUE!' }, '=PRODUCT(2, #N/A)']),
  m('QUOTIENT', 'QUOTIENT(numerator, denominator)', 'Returns the integer portion of a division (truncated toward zero).', ['=QUOTIENT(5, 2)', '=QUOTIENT(4.5, 3.1)', '=QUOTIENT(-10, 3)', '=QUOTIENT(10, -3)', { f: '=QUOTIENT(1, 0)', expect: { error: '#DIV/0!' }, why: 'division by zero' }, '=QUOTIENT("x", 2)']),
  m('RADIANS', 'RADIANS(angle)', 'Converts degrees to radians.', ['=RADIANS(270)', '=RADIANS(180)', '=RADIANS(-45)', '=RADIANS(0)', '=RADIANS("x")']),
  m('ROMAN', 'ROMAN(number)', 'Converts a number (0 to 3999, truncated) to a classic roman numeral.', ['=ROMAN(499)', '=ROMAN(1999)', '=ROMAN(3999)', { f: '=ROMAN(4.9)', expect: 'IV', why: 'the number is truncated' }, { f: '=ROMAN(0)', expect: '', why: 'Excel returns empty text for 0' }, { f: '=ROMAN(4000)', expect: { error: '#VALUE!' }, why: 'out of range' }, { f: '=ROMAN(-1)', expect: { error: '#VALUE!' }, why: 'negative' }]),
  m('ROUND', 'ROUND(number, num_digits)', 'Rounds a number to a number of digits, halves away from zero.', [
    '=ROUND(2.15, 1)', '=ROUND(2.149, 1)', '=ROUND(-1.475, 2)', '=ROUND(21.5, -1)', '=ROUND(626.3, -3)', '=ROUND(2.5, 0)', '=ROUND(-2.5, 0)',
    { f: '=ROUND(1.005, 2)', expect: 1.01, why: 'formula.js rounds the binary value (1.00); Excel rounds the decimal value' },
    { f: '=ROUND(1234.5678, -1.5)', expect: 1230, why: 'num_digits is truncated toward zero (-1); formula.js does not truncate' },
    { f: '=ROUND(1234.5678, 2.9)', expect: 1234.57, why: 'num_digits is truncated toward zero (2)' },
    '=ROUND("x", 1)',
  ]),
  m('ROUNDDOWN', 'ROUNDDOWN(number, num_digits)', 'Rounds a number toward zero to a number of digits.', [
    '=ROUNDDOWN(3.2, 0)', '=ROUNDDOWN(76.9, 0)', '=ROUNDDOWN(3.14159, 3)', '=ROUNDDOWN(-3.14159, 1)', '=ROUNDDOWN(31415.92654, -2)',
    { f: '=ROUNDDOWN(1234.5678, -1.5)', expect: 1230, why: 'num_digits is truncated toward zero (-1)' },
    '=ROUNDDOWN("x", 1)',
  ]),
  m('ROUNDUP', 'ROUNDUP(number, num_digits)', 'Rounds a number away from zero to a number of digits.', [
    '=ROUNDUP(3.2, 0)', '=ROUNDUP(76.9, 0)', '=ROUNDUP(3.14159, 3)', '=ROUNDUP(-3.14159, 1)', '=ROUNDUP(31415.92654, -2)',
    { f: '=ROUNDUP(1234.5678, -1.5)', expect: 1240, why: 'num_digits is truncated toward zero (-1)' },
    '=ROUNDUP("x", 1)',
  ]),
  m('SEC', 'SEC(number)', 'Returns the secant of an angle in radians.', ['=SEC(45)', '=SEC(0)', '=SEC(-1)', '=SEC(PI())', '=SEC("x")']),
  m('SECH', 'SECH(number)', 'Returns the hyperbolic secant of a number.', ['=SECH(45)', '=SECH(0)', '=SECH(-1)', '=SECH(0.5)', '=SECH("x")']),
  m('SIGN', 'SIGN(number)', 'Returns 1, 0 or -1 according to the sign of a number.', ['=SIGN(10)', '=SIGN(4-4)', '=SIGN(-0.00001)', '=SIGN("-3")', '=SIGN("x")']),
  m('SIN', 'SIN(number)', 'Returns the sine of an angle in radians.', ['=SIN(PI())', '=SIN(PI()/2)', '=SIN(30*PI()/180)', '=SIN(-1)', '=SIN("x")']),
  m('SINH', 'SINH(number)', 'Returns the hyperbolic sine of a number.', ['=SINH(1)', '=SINH(-1)', '=SINH(0)', '=SINH(2.5)', { f: '=SINH(1000)', expect: { error: '#NUM!' }, why: 'overflow' }, '=SINH("x")']),
  m('SQRT', 'SQRT(number)', 'Returns the positive square root of a number.', ['=SQRT(16)', '=SQRT(2)', '=SQRT(0)', '=SQRT(0.25)', '=SQRT(-16)', '=SQRT("x")']),
  m('SQRTPI', 'SQRTPI(number)', 'Returns the square root of (number * pi).', ['=SQRTPI(1)', '=SQRTPI(2)', '=SQRTPI(0)', '=SQRTPI(-1)', '=SQRTPI("x")']),
  m('SUM', 'SUM(number1, [number2], ...)', 'Adds its arguments. Text and booleans typed directly are converted; inside arrays they are ignored.', [
    '=SUM(1, 2, 3)', '=SUM({1, 2; 3, 4})', '=SUM({1, "a", TRUE}, 2)', { f: '=SUM("3", TRUE)', expect: 4, why: 'a boolean typed directly counts as 1' }, '=SUM(-1.5, 0.25)', '=SUM()',
    { f: '=SUM(1, "abc")', expect: { error: '#VALUE!' }, why: 'formula.js ignores the text; Excel returns #VALUE! for unparseable direct text' },
    '=SUM({1, #N/A})',
  ]),
  m('SUMIF', 'SUMIF(range, criteria, [sum_range])', 'Adds the cells (of sum_range, or range) whose range cell meets the criteria.', [
    '=SUMIF({1, 2, 3, 4}, ">2")', '=SUMIF({"a", "b", "a"}, "a", {10, 20, 30})', '=SUMIF({1, 2, 3, 4}, "<>2")', { f: '=SUMIF({"apple", "avocado", "banana"}, "a*", {1, 2, 3})', expect: 3, why: 'criteria support wildcards' },
    '=SUMIF({1, 2, 3}, 2)', '=SUMIF({1, 2, 3}, ">5")', '=SUMIF({"x", 5, 6}, ">=5")',
  ]),
  m('SUMIFS', 'SUMIFS(sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Adds the cells of sum_range that meet every (criteria_range, criteria) pair.', [
    '=SUMIFS({10, 20, 30, 40}, {"a", "b", "a", "b"}, "a")', '=SUMIFS({10, 20, 30, 40}, {"a", "b", "a", "b"}, "b", {1, 2, 3, 4}, ">2")', '=SUMIFS({1, 2, 3}, {1, 2, 3}, ">=2")',
    '=SUMIFS({1, 2, 3}, {"x", "y", "z"}, "q")', { f: '=SUMIFS({1, 2, 3}, {1, 2}, ">0")', expect: { error: '#VALUE!' }, why: 'ranges of different shapes' },
  ]),
  m('SUMPRODUCT', 'SUMPRODUCT(array1, [array2], ...)', 'Multiplies corresponding array cells and returns the sum of the products; non-numbers count as 0.', [
    '=SUMPRODUCT({1, 2, 3}, {4, 5, 6})', '=SUMPRODUCT({1, 2; 3, 4}, {5, 6; 7, 8})', '=SUMPRODUCT({1, 2, 3})', { f: '=SUMPRODUCT({1, "a", 3}, {4, 5, 6})', expect: 22, why: 'non-numeric cells count as 0' }, '=SUMPRODUCT({1, 2}, {1, 2}, {3, 4})',
    { f: '=SUMPRODUCT({1, 2}, {1, 2, 3})', expect: { error: '#VALUE!' }, why: 'arrays of different shapes' },
  ]),
  m('SUMSQ', 'SUMSQ(number1, [number2], ...)', 'Returns the sum of the squares of its arguments.', ['=SUMSQ(3, 4)', '=SUMSQ({1, 2, 3})', { f: '=SUMSQ({1, "a", TRUE}, 2)', expect: 5, why: 'text and booleans inside arrays are ignored' }, '=SUMSQ(-2.5)', '=SUMSQ("3")', { f: '=SUMSQ(1, "x")', expect: { error: '#VALUE!' }, why: 'unparseable direct text' }]),
  m('SUMX2MY2', 'SUMX2MY2(array_x, array_y)', 'Returns the sum of the differences of squares of corresponding values.', ['=SUMX2MY2({2, 3, 9, 1, 8, 7, 5}, {6, 5, 11, 7, 5, 4, 4})', '=SUMX2MY2({1, 2}, {3, 4})', { f: '=SUMX2MY2({1, "a", 3}, {1, 2, 3})', expect: 0, why: 'pairs with a non-number are skipped' }, '=SUMX2MY2(5, 3)', { f: '=SUMX2MY2({1, 2}, {1, 2, 3})', expect: { error: '#N/A' }, why: 'arrays of different sizes' }]),
  m('SUMX2PY2', 'SUMX2PY2(array_x, array_y)', 'Returns the sum of the sums of squares of corresponding values.', ['=SUMX2PY2({2, 3, 9, 1, 8, 7, 5}, {6, 5, 11, 7, 5, 4, 4})', '=SUMX2PY2({1, 2}, {3, 4})', { f: '=SUMX2PY2({1, TRUE, 3}, {1, 2, 3})', expect: 20, why: 'pairs with a non-number are skipped' }, '=SUMX2PY2(5, 3)', { f: '=SUMX2PY2({1, 2}, {1, 2, 3})', expect: { error: '#N/A' }, why: 'arrays of different sizes' }]),
  m('SUMXMY2', 'SUMXMY2(array_x, array_y)', 'Returns the sum of squares of differences of corresponding values.', ['=SUMXMY2({2, 3, 9, 1, 8, 7, 5}, {6, 5, 11, 7, 5, 4, 4})', '=SUMXMY2({1, 2}, {3, 4})', { f: '=SUMXMY2({1, "a", 3}, {1, 2, 5})', expect: 4, why: 'pairs with a non-number are skipped' }, '=SUMXMY2(5, 3)', { f: '=SUMXMY2({1, 2}, {1, 2, 3})', expect: { error: '#N/A' }, why: 'arrays of different sizes' }]),
  m('TAN', 'TAN(number)', 'Returns the tangent of an angle in radians.', ['=TAN(0.785)', '=TAN(45*PI()/180)', '=TAN(0)', '=TAN(-1)', '=TAN("x")']),
  m('TANH', 'TANH(number)', 'Returns the hyperbolic tangent of a number.', ['=TANH(-2)', '=TANH(0)', '=TANH(0.5)', '=TANH(100)', '=TANH("x")']),
  m('TRUNC', 'TRUNC(number, [num_digits])', 'Truncates a number toward zero to a number of digits (0 by default).', ['=TRUNC(8.9)', '=TRUNC(-8.9)', '=TRUNC(0.45)', '=TRUNC(3.14159, 2)', '=TRUNC(-3.14159, 3)', '=TRUNC(1234.567, -2)', { f: '=TRUNC(1234.567, -1.5)', expect: 1230, why: 'num_digits is truncated toward zero (-1)' }, '=TRUNC("x")']),
  m('SERIESSUM', 'SERIESSUM(x, n, m, coefficients)', 'Returns the sum of a power series a1*x^n + a2*x^(n+m) + ...', [{ f: '=SERIESSUM(PI()/4, 0, 2, {1, -0.5, 0.041666667, -0.001388889})', expect: 0.7071032149236011, why: 'formula.js cannot take array coefficients; computed by hand' }, { f: '=SERIESSUM(2, 1, 1, {1, 1, 1})', expect: 14, why: '2 + 4 + 8' }, { f: '=SERIESSUM(0.5, 0, 1, 3)', expect: 3, why: 'single coefficient' }, { f: '=SERIESSUM(1, 2, 3, {2, 4})', expect: 6, why: '2*1^2 + 4*1^5' }, '=SERIESSUM("x", 0, 1, {1})']),
  m('MMULT', 'MMULT(array1, array2)', 'Returns the matrix product of two arrays.', [
    '=MMULT({1, 2; 3, 4}, {5, 6; 7, 8})', '=MMULT({1, 2, 3}, {4; 5; 6})', '=MMULT({1; 2}, {3, 4})', '=MMULT({0.5, 1.5}, {2; 4})',
    { f: '=MMULT({1, 2}, {1, 2})', expect: { error: '#VALUE!' }, why: 'columns of array1 must equal rows of array2' },
    { f: '=MMULT({1, "a"}, {1; 2})', expect: { error: '#VALUE!' }, why: 'non-numeric cell' },
  ]),
  m('MUNIT', 'MUNIT(dimension)', 'Returns the identity matrix of a dimension.', ['=MUNIT(1)', '=MUNIT(2)', '=MUNIT(3)', { f: '=MUNIT(0)', expect: { error: '#VALUE!' }, why: 'dimension must be > 0' }, { f: '=MUNIT("x")', expect: { error: '#VALUE!' }, why: 'not a number' }]),
  m('DECIMAL', 'DECIMAL(text, radix)', 'Converts a text representation of a number in a base (2-36) to a decimal number.', [
    '=DECIMAL("FF", 16)', '=DECIMAL("111", 2)', '=DECIMAL("zap", 36)', '=DECIMAL("FFFFFFFFFF", 16)', '=DECIMAL("1111111111", 2)',
    { f: '=DECIMAL("12", 2)', expect: { error: '#NUM!' }, why: 'digit not valid in the base' }, '=DECIMAL("10", 37)',
  ]),
  m('BASE', 'BASE(number, radix, [min_length])', 'Converts a non-negative integer into text in a base (2-36), optionally zero-padded to min_length.', [
    '=BASE(7, 2)', '=BASE(100, 16)', '=BASE(15, 2, 10)', '=BASE(1000, 2)', { f: '=BASE(12345, 36)', expect: '9IX', why: 'Excel returns upper-case digits' }, { f: '=BASE(255, 16, 1)', expect: 'FF', why: 'Excel returns upper-case digits; min_length only pads' }, { f: '=BASE(-1, 2)', expect: { error: '#NUM!' }, why: 'negative numbers give #NUM!' }, { f: '=BASE(10, 1)', expect: { error: '#NUM!' }, why: 'radix must be 2..36' },
  ]),
];
