import type { FnSpec } from '../types.ts';

const s = (name: string, signature: string, summary: string, cases: FnSpec['cases']): FnSpec => ({ name, category: 'statistical', signature, summary, cases });

const DATA = '{3, 4, 5, 2, 3, 4, 5, 6, 4, 7}';

export const statistical: FnSpec[] = [
  s('AVERAGE', 'AVERAGE(number1, [number2], ...)', 'Returns the arithmetic mean of the numbers (text and booleans inside arrays are ignored).', [
    '=AVERAGE(10, 7, 9, 27, 2)', `=AVERAGE(${DATA})`, '=AVERAGE({1, "a", TRUE}, 3)', { f: '=AVERAGE("4", TRUE)', expect: 2.5, why: 'numeric text and booleans typed directly are counted' }, '=AVERAGE(-1.5, 2.5)',
    { f: '=AVERAGE({"a", "b"})', expect: { error: '#DIV/0!' }, why: 'no numbers' }, '=AVERAGE(1, #N/A)',
  ]),
  s('AVERAGEA', 'AVERAGEA(value1, [value2], ...)', 'Returns the mean of the values, counting text inside arrays as 0 and booleans as 1 or 0.', [
    '=AVERAGEA(10, 7, 9, 2)', '=AVERAGEA({1, "a", TRUE}, 3)', '=AVERAGEA({2, FALSE})', { f: '=AVERAGEA("4", TRUE)', expect: 2.5, why: 'numeric text and booleans typed directly are counted' }, '=AVERAGEA({"x", "y", 6})',
    { f: '=AVERAGEA(1, "abc")', expect: { error: '#VALUE!' }, why: 'unparseable direct text' }, '=AVERAGEA({1, #DIV/0!})',
  ]),
  s('AVEDEV', 'AVEDEV(number1, [number2], ...)', 'Returns the average of the absolute deviations of the numbers from their mean.', [
    '=AVEDEV(4, 5, 6, 7, 5, 4, 3)', `=AVEDEV(${DATA})`, { f: '=AVEDEV({1, "a", TRUE}, 3)', expect: 1, why: 'text and booleans inside arrays are ignored' }, '=AVEDEV(5)', { f: '=AVEDEV({"a"})', expect: { error: '#NUM!' }, why: 'no numbers' }, '=AVEDEV(1, #N/A)',
  ]),
  s('AVERAGEIF', 'AVERAGEIF(range, criteria, [average_range])', 'Returns the mean of the cells (of average_range, or range) whose range cell meets the criteria.', [
    '=AVERAGEIF({100, 200, 300, 400}, "<250")', '=AVERAGEIF({"a", "b", "a"}, "a", {10, 20, 40})', '=AVERAGEIF({1, 2, 3, 4}, ">=2")', { f: '=AVERAGEIF({"apple", "avocado", "kiwi"}, "a*", {2, 4, 9})', expect: 3, why: 'criteria support wildcards' },
    { f: '=AVERAGEIF({1, 2, 3}, ">5")', expect: { error: '#DIV/0!' }, why: 'no cell meets the criteria' },
  ]),
  s('AVERAGEIFS', 'AVERAGEIFS(average_range, criteria_range1, criteria1, ...)', 'Returns the mean of the average_range cells that meet every criterion.', [
    '=AVERAGEIFS({10, 20, 30, 40}, {"a", "b", "a", "b"}, "b")', '=AVERAGEIFS({10, 20, 30, 40}, {1, 2, 3, 4}, ">1", {1, 2, 3, 4}, "<4")', '=AVERAGEIFS({5, 6}, {"x", "y"}, "x")',
    { f: '=AVERAGEIFS({1, 2}, {1, 2}, ">5")', expect: { error: '#DIV/0!' }, why: 'no cell meets the criteria' },
    { f: '=AVERAGEIFS({1, 2, 3}, {1, 2}, ">0")', expect: { error: '#VALUE!' }, why: 'ranges of different shapes' },
  ]),
  s('COUNT', 'COUNT(value1, [value2], ...)', 'Counts numbers: numbers anywhere, plus numeric text and booleans typed directly as arguments.', [
    '=COUNT(1, 2, 3)', '=COUNT({1, "a", TRUE, 2})', { f: '=COUNT("1", TRUE, "x")', expect: 2, why: 'numeric text and booleans typed directly are counted' }, '=COUNT({#N/A, 1})', '=COUNT()', '=COUNT(#DIV/0!, 1)',
  ]),
  s('COUNTA', 'COUNTA(value1, [value2], ...)', 'Counts the values that are not empty (errors and empty text count).', [
    '=COUNTA(1, "a", TRUE)', { f: '=COUNTA({1, "", #N/A})', expect: 3, why: 'empty text and errors are values' }, { f: '=COUNTA("")', expect: 1, why: 'empty text is a value' }, '=COUNTA({1, 2; 3, 4}, 5)', '=COUNTA(#DIV/0!)',
  ]),
  s('COUNTBLANK', 'COUNTBLANK(range)', 'Counts the empty cells and empty texts in a range.', ['=COUNTBLANK({1, "", "a", ""})', '=COUNTBLANK({1, 2})', '=COUNTBLANK("")', '=COUNTBLANK(5)']),
  s('COUNTIF', 'COUNTIF(range, criteria)', 'Counts the cells that meet the criteria.', [
    '=COUNTIF({"apples", "oranges", "peaches", "apples"}, "apples")', '=COUNTIF({32, 54, 75, 86}, ">55")', '=COUNTIF({32, 54, 75, 86}, "<>75")', { f: '=COUNTIF({"apples", "oranges", "Apples"}, "a*")', expect: 2, why: 'wildcards, case-insensitive' },
    { f: '=COUNTIF({"apples", "oranges", "peaches"}, "?????es")', expect: 2, why: '? matches exactly one character' }, '=COUNTIF({1, 2, 2, 3}, 2)', { f: '=COUNTIF({TRUE, FALSE, TRUE}, TRUE)', expect: 2, why: 'boolean criteria match booleans' }, { f: '=COUNTIF({"x", "", "y"}, "")', expect: 1, why: 'an empty criterion matches empty text' },
  ]),
  s('COUNTIFS', 'COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Counts the positions where every range meets its criterion.', [
    '=COUNTIFS({"a", "b", "a", "a"}, "a", {1, 2, 3, 4}, ">1")', '=COUNTIFS({1, 2, 3, 4}, ">=2")', '=COUNTIFS({"x", "y"}, "z")', { f: '=COUNTIFS({"Yes", "No", "yes"}, "yes", {1, 1, 0}, 1)', expect: 1, why: 'text criteria are case-insensitive' },
    { f: '=COUNTIFS({1, 2}, ">0", {1, 2, 3}, ">0")', expect: { error: '#VALUE!' }, why: 'ranges of different shapes' },
  ]),
  s('MAX', 'MAX(number1, [number2], ...)', 'Returns the largest number (text and booleans inside arrays are ignored; 0 when there are none).', [
    '=MAX(10, 7, 9, 27, 2)', `=MAX(${DATA})`, '=MAX({1, "a", TRUE}, -3)', { f: '=MAX("40", TRUE)', expect: 40, why: 'numeric text typed directly is counted' }, '=MAX({"x"})', '=MAX(-5, -2)', '=MAX(1, #N/A)',
  ]),
  s('MIN', 'MIN(number1, [number2], ...)', 'Returns the smallest number (text and booleans inside arrays are ignored; 0 when there are none).', [
    '=MIN(10, 7, 9, 27, 2)', `=MIN(${DATA})`, '=MIN({5, "a", FALSE}, 3)', { f: '=MIN("-4", TRUE)', expect: -4, why: 'numeric text typed directly is counted' }, '=MIN({"x"})', '=MIN(-5, -2)', '=MIN(1, #N/A)',
  ]),
  s('MAXIFS', 'MAXIFS(max_range, criteria_range1, criteria1, ...)', 'Returns the largest max_range cell that meets every criterion (0 when none).', [
    '=MAXIFS({89, 93, 96, 85, 91, 88}, {1, 2, 2, 3, 1, 1}, 1)', '=MAXIFS({10, 1, 100}, {"b", "a", "b"}, "b", {1, 1, 0}, 1)', '=MAXIFS({1, 2}, {"x", "y"}, "z")', '=MAXIFS({-5, -2, -9}, {1, 1, 1}, 1)',
    { f: '=MAXIFS({1, 2, 3}, {1, 2}, ">0")', expect: { error: '#VALUE!' }, why: 'ranges of different shapes' },
  ]),
  s('MINIFS', 'MINIFS(min_range, criteria_range1, criteria1, ...)', 'Returns the smallest min_range cell that meets every criterion (0 when none).', [
    '=MINIFS({89, 93, 96, 85, 91, 88}, {1, 2, 2, 3, 1, 1}, 1)', '=MINIFS({10, 1, 100}, {"b", "a", "b"}, "b")', '=MINIFS({1, 2}, {"x", "y"}, "z")', '=MINIFS({5, 2, 9}, {1, 1, 0}, 1)',
    { f: '=MINIFS({1, 2, 3}, {1, 2}, ">0")', expect: { error: '#VALUE!' }, why: 'ranges of different shapes' },
  ]),
  s('MEDIAN', 'MEDIAN(number1, [number2], ...)', 'Returns the median of the numbers.', [
    '=MEDIAN(1, 2, 3, 4, 5)', '=MEDIAN(1, 2, 3, 4, 5, 6)', `=MEDIAN(${DATA})`, { f: '=MEDIAN({3, "a", TRUE}, 1)', expect: 2, why: 'text and booleans inside arrays are ignored' }, '=MEDIAN(7)', { f: '=MEDIAN({"a"})', expect: { error: '#NUM!' }, why: 'no numbers' }, '=MEDIAN(1, #N/A)',
  ]),
  s('MODE.SNGL', 'MODE.SNGL(number1, [number2], ...)', 'Returns the most frequent number (the first one to reach the highest count); #N/A when no number repeats.', [
    '=MODE.SNGL(5.6, 4, 4, 3, 2, 4)', `=MODE.SNGL(${DATA})`, '=MODE.SNGL({1, 2, 2, 1})', { f: '=MODE.SNGL({1, "a", "a", 3, 3})', expect: 3, why: 'text inside arrays is ignored' }, { f: '=MODE.SNGL(1, 2, 3)', expect: { error: '#N/A' }, why: 'no value repeats' }, '=MODE.SNGL(1, #N/A)',
  ]),
  s('LARGE', 'LARGE(array, k)', 'Returns the k-th largest number in an array.', ['=LARGE({3, 5, 3, 5, 4}, 3)', `=LARGE(${DATA}, 1)`, '=LARGE({3, 5, 3, 5, 4}, 2)', '=LARGE({1, "a", 2}, 2)', { f: '=LARGE({1, 2}, 3)', expect: { error: '#NUM!' }, why: 'k larger than the count' }, { f: '=LARGE({1, 2}, 0)', expect: { error: '#NUM!' }, why: 'k must be >= 1' }]),
  s('SMALL', 'SMALL(array, k)', 'Returns the k-th smallest number in an array.', ['=SMALL({3, 5, 3, 5, 4}, 3)', `=SMALL(${DATA}, 1)`, '=SMALL({3, 5, 3, 5, 4}, 2)', { f: '=SMALL({1, "a", 2}, 2)', expect: 2, why: 'text inside arrays is ignored' }, { f: '=SMALL({1, 2}, 3)', expect: { error: '#NUM!' }, why: 'k larger than the count' }, { f: '=SMALL({1, 2}, 0)', expect: { error: '#NUM!' }, why: 'k must be >= 1' }]),
  s('GEOMEAN', 'GEOMEAN(number1, [number2], ...)', 'Returns the geometric mean of positive numbers.', ['=GEOMEAN(4, 5, 8, 7, 11, 4, 3)', `=GEOMEAN(${DATA})`, { f: '=GEOMEAN({2, "a", 8})', expect: 4, why: 'text inside arrays is ignored' }, '=GEOMEAN(5)', { f: '=GEOMEAN(1, 0)', expect: { error: '#NUM!' }, why: 'values must be positive' }, '=GEOMEAN(1, -2)']),
  s('HARMEAN', 'HARMEAN(number1, [number2], ...)', 'Returns the harmonic mean of positive numbers.', ['=HARMEAN(4, 5, 8, 7, 11, 4, 3)', `=HARMEAN(${DATA})`, { f: '=HARMEAN({2, "a", 8})', expect: 3.2, why: 'text inside arrays is ignored' }, '=HARMEAN(5)', { f: '=HARMEAN(1, 0)', expect: { error: '#NUM!' }, why: 'values must be positive' }, { f: '=HARMEAN(1, -2)', expect: { error: '#NUM!' }, why: 'values must be positive' }]),
  s('DEVSQ', 'DEVSQ(number1, [number2], ...)', 'Returns the sum of squared deviations of the numbers from their mean.', ['=DEVSQ(4, 5, 8, 7, 11, 4, 3)', `=DEVSQ(${DATA})`, { f: '=DEVSQ({1, "a", TRUE}, 3)', expect: 2, why: 'text and booleans inside arrays are ignored' }, '=DEVSQ(5)', { f: '=DEVSQ({"a"})', expect: { error: '#NUM!' }, why: 'no numbers' }, '=DEVSQ(1, #N/A)']),
  s('VAR.S', 'VAR.S(number1, [number2], ...)', 'Returns the sample variance of the numbers.', ['=VAR.S(1345, 1301, 1368, 1322, 1310, 1370, 1318, 1350, 1303, 1299)', `=VAR.S(${DATA})`, '=VAR.S({1, "a", TRUE}, 3)', '=VAR.S(2, 4)', { f: '=VAR.S(5)', expect: { error: '#DIV/0!' }, why: 'needs two values' }, { f: '=VAR.S(1, #N/A)', expect: { error: '#N/A' }, why: 'errors propagate' }]),
  s('VAR.P', 'VAR.P(number1, [number2], ...)', 'Returns the population variance of the numbers.', ['=VAR.P(1345, 1301, 1368, 1322, 1310, 1370, 1318, 1350, 1303, 1299)', `=VAR.P(${DATA})`, '=VAR.P({1, "a", TRUE}, 3)', '=VAR.P(2, 4)', '=VAR.P(5)', { f: '=VAR.P({"a"})', expect: { error: '#DIV/0!' }, why: 'no numbers' }]),
  s('STDEV.S', 'STDEV.S(number1, [number2], ...)', 'Returns the sample standard deviation of the numbers.', ['=STDEV.S(1345, 1301, 1368, 1322, 1310, 1370, 1318, 1350, 1303, 1299)', `=STDEV.S(${DATA})`, '=STDEV.S({1, "a", TRUE}, 3)', '=STDEV.S(2, 4)', { f: '=STDEV.S(5)', expect: { error: '#DIV/0!' }, why: 'needs two values' }, { f: '=STDEV.S(1, #N/A)', expect: { error: '#N/A' }, why: 'errors propagate' }]),
  s('STDEV.P', 'STDEV.P(number1, [number2], ...)', 'Returns the population standard deviation of the numbers.', ['=STDEV.P(1345, 1301, 1368, 1322, 1310, 1370, 1318, 1350, 1303, 1299)', `=STDEV.P(${DATA})`, '=STDEV.P({1, "a", TRUE}, 3)', '=STDEV.P(2, 4)', '=STDEV.P(5)', { f: '=STDEV.P({"a"})', expect: { error: '#DIV/0!' }, why: 'no numbers' }]),
  s('SKEW', 'SKEW(number1, [number2], ...)', 'Returns the sample skewness of the numbers.', [`=SKEW(${DATA})`, '=SKEW(1, 2, 3, 10)', { f: '=SKEW({1, "a", 2, 9})', expect: 1.6300591617118863, why: 'text inside arrays is ignored' }, { f: '=SKEW(1, 2)', expect: { error: '#DIV/0!' }, why: 'needs three values' }, { f: '=SKEW(2, 2, 2)', expect: { error: '#DIV/0!' }, why: 'zero spread' }, '=SKEW(1, #N/A, 3)']),
  s('SKEW.P', 'SKEW.P(number1, [number2], ...)', 'Returns the population skewness of the numbers.', [`=SKEW.P(${DATA})`, '=SKEW.P(1, 2, 3, 10)', { f: '=SKEW.P({1, "a", 2, 9})', expect: 0.6654688661238354, why: 'text inside arrays is ignored' }, '=SKEW.P(1, 2)', { f: '=SKEW.P(2, 2, 2)', expect: { error: '#DIV/0!' }, why: 'zero spread' }, '=SKEW.P(1, #N/A, 3)']),
  s('KURT', 'KURT(number1, [number2], ...)', 'Returns the sample excess kurtosis of the numbers.', [`=KURT(${DATA})`, '=KURT(1, 2, 3, 10, 4)', { f: '=KURT({1, "a", 2, 9, 4})', expect: 1.5, why: 'text inside arrays is ignored' }, { f: '=KURT(1, 2, 3)', expect: { error: '#DIV/0!' }, why: 'needs four values' }, { f: '=KURT(2, 2, 2, 2)', expect: { error: '#DIV/0!' }, why: 'zero spread' }, '=KURT(1, #N/A, 3, 4)']),
  s('PERCENTILE.INC', 'PERCENTILE.INC(array, k)', 'Returns the k-th percentile (0 <= k <= 1) of the numbers, interpolating between values.', ['=PERCENTILE.INC({1, 3, 2, 4}, 0.3)', `=PERCENTILE.INC(${DATA}, 0.9)`, '=PERCENTILE.INC({10, 20}, 0)', '=PERCENTILE.INC({10, 20}, 1)', { f: '=PERCENTILE.INC({1, "a", 3}, 0.5)', expect: 2, why: 'text inside arrays is ignored' }, '=PERCENTILE.INC({1, 2}, 1.5)', '=PERCENTILE.INC({1, 2}, -0.1)']),
  s('PERCENTILE.EXC', 'PERCENTILE.EXC(array, k)', 'Returns the k-th percentile (0 < k < 1, exclusive) of the numbers, interpolating between values.', ['=PERCENTILE.EXC({1, 2, 3, 6, 6, 6, 7, 8, 9}, 0.25)', `=PERCENTILE.EXC(${DATA}, 0.5)`, '=PERCENTILE.EXC({1, 2, 3, 4}, 0.4)', { f: '=PERCENTILE.EXC({1, "a", 3, 5}, 0.5)', expect: 3, why: 'text inside arrays is ignored' }, '=PERCENTILE.EXC({1, 2, 3}, 0.1)', '=PERCENTILE.EXC({1, 2, 3}, 0)', '=PERCENTILE.EXC({1, 2, 3}, 1)']),
  s('QUARTILE.INC', 'QUARTILE.INC(array, quart)', 'Returns a quartile (0-4) of the numbers.', ['=QUARTILE.INC({1, 2, 4, 7, 8, 9, 10, 12}, 1)', `=QUARTILE.INC(${DATA}, 3)`, { f: '=QUARTILE.INC({1, 2, 3}, 0)', expect: 1, why: 'quart 0 is the minimum' }, { f: '=QUARTILE.INC({1, 2, 3}, 4)', expect: 3, why: 'quart 4 is the maximum' }, { f: '=QUARTILE.INC({1, 2, 3, 4}, 2.7)', expect: 2.5, why: 'quart is truncated to 2 (the median)' }, '=QUARTILE.INC({1, 2}, 5)', '=QUARTILE.INC({1, 2}, -1)']),
  s('RANK.EQ', 'RANK.EQ(number, ref, [order])', 'Returns the rank of a number in a list (descending by default, ascending when order is non-zero); ties share the best rank.', ['=RANK.EQ(7, {7, 3.5, 3.5, 1, 2}, 1)', '=RANK.EQ(2, {7, 3.5, 3.5, 1, 2})', '=RANK.EQ(3.5, {7, 3.5, 3.5, 1, 2})', '=RANK.EQ(3.5, {7, 3.5, 3.5, 1, 2}, 1)', { f: '=RANK.EQ(4, {7, 3.5, 3.5, 1, 2})', expect: { error: '#N/A' }, why: 'number not in the list' }, { f: '=RANK.EQ(1, {1, "a", 3})', expect: 2, why: 'text inside the list is ignored' }]),
  s('RANK.AVG', 'RANK.AVG(number, ref, [order])', 'Returns the rank of a number in a list; tied numbers get the average of their ranks.', ['=RANK.AVG(94, {89, 88, 92, 101, 94, 97, 95})', '=RANK.AVG(3.5, {7, 3.5, 3.5, 1, 2})', '=RANK.AVG(3.5, {7, 3.5, 3.5, 1, 2}, 1)', '=RANK.AVG(2, {2, 2, 2})', '=RANK.AVG(7, {7, 3.5, 3.5, 1, 2}, 1)', { f: '=RANK.AVG(4, {7, 3.5, 3.5, 1, 2})', expect: { error: '#N/A' }, why: 'number not in the list' }]),
  s('TRIMMEAN', 'TRIMMEAN(array, percent)', 'Returns the mean after excluding a percentage of the smallest and largest numbers.', ['=TRIMMEAN({4, 5, 6, 7, 2, 3, 4, 5, 1, 2, 3}, 0.2)', `=TRIMMEAN(${DATA}, 0.4)`, '=TRIMMEAN({1, 2, 3}, 0)', '=TRIMMEAN({1, 2, 3, 100}, 0.5)', '=TRIMMEAN({1, 2}, 1)', { f: '=TRIMMEAN({1, 2}, -0.1)', expect: { error: '#NUM!' }, why: 'percent must be in [0, 1)' }]),
  s('STANDARDIZE', 'STANDARDIZE(x, mean, standard_dev)', 'Returns (x - mean) / standard_dev.', ['=STANDARDIZE(42, 40, 1.5)', '=STANDARDIZE(10, 10, 2)', '=STANDARDIZE(-1, 2, 0.5)', '=STANDARDIZE(1, 2, 0)', '=STANDARDIZE("x", 1, 1)']),
  s('CORREL', 'CORREL(array1, array2)', 'Returns the correlation coefficient of two arrays.', ['=CORREL({3, 2, 4, 5, 6}, {9, 7, 12, 15, 17})', '=CORREL({1, 2, 3}, {3, 2, 1})', { f: '=CORREL({1, "a", 3, 4}, {2, 5, 6, 9})', expect: 0.9941916256019199, why: 'pairs with a non-number are skipped' }, { f: '=CORREL({1, 1, 1}, {1, 2, 3})', expect: { error: '#DIV/0!' }, why: 'zero spread' }, { f: '=CORREL({1, 2}, {1, 2, 3})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('PEARSON', 'PEARSON(array1, array2)', 'Returns the Pearson product-moment correlation coefficient.', ['=PEARSON({9, 7, 5, 3, 1}, {10, 6, 1, 5, 3})', '=PEARSON({1, 2, 3}, {2, 4, 6})', { f: '=PEARSON({1, TRUE, 3, 4}, {2, 5, 6, 9})', expect: 0.9941916256019199, why: 'pairs with a non-number are skipped' }, { f: '=PEARSON({2, 2}, {1, 3})', expect: { error: '#DIV/0!' }, why: 'zero spread' }, { f: '=PEARSON({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('RSQ', 'RSQ(known_ys, known_xs)', 'Returns the square of the Pearson correlation coefficient.', ['=RSQ({2, 3, 9, 1, 8, 7, 5}, {6, 5, 11, 7, 5, 4, 4})', '=RSQ({1, 2, 3}, {2, 4, 6})', { f: '=RSQ({1, "a", 3, 4}, {2, 5, 6, 9})', expect: 0.988416988416988, why: 'pairs with a non-number are skipped' }, { f: '=RSQ({1, 1}, {1, 2})', expect: { error: '#DIV/0!' }, why: 'zero spread' }, { f: '=RSQ({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('SLOPE', 'SLOPE(known_ys, known_xs)', 'Returns the slope of the least-squares regression line.', ['=SLOPE({2, 3, 9, 1, 8, 7, 5}, {6, 5, 11, 7, 5, 4, 4})', '=SLOPE({2, 4, 6}, {1, 2, 3})', { f: '=SLOPE({1, "a", 3, 4}, {2, 5, 6, 9})', expect: 0.4324324324324324, why: 'pairs with a non-number are skipped' }, { f: '=SLOPE({1, 2}, {3, 3})', expect: { error: '#DIV/0!' }, why: 'all x equal' }, { f: '=SLOPE({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('INTERCEPT', 'INTERCEPT(known_ys, known_xs)', 'Returns the y-intercept of the least-squares regression line.', [{ f: '=INTERCEPT({2, 3, 9, 1, 8}, {6, 5, 11, 7, 5})', expect: 0.04838709677419306, why: 'formula.js INTERCEPT fails on arrays; computed by hand' }, { f: '=INTERCEPT({3, 5, 7}, {1, 2, 3})', expect: 1, why: 'formula.js INTERCEPT fails on arrays; computed by hand' }, { f: '=INTERCEPT({1, "a", 3, 4}, {2, 5, 6, 9})', expect: 0.21621621621621623, why: 'pairs with a non-number are skipped' }, { f: '=INTERCEPT({1, 2}, {3, 3})', expect: { error: '#DIV/0!' }, why: 'all x equal' }, { f: '=INTERCEPT({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('STEYX', 'STEYX(known_ys, known_xs)', 'Returns the standard error of the predicted y for each x in a regression.', ['=STEYX({2, 3, 9, 1, 8, 7, 5}, {6, 5, 11, 7, 5, 4, 4})', '=STEYX({1, 3, 2, 5}, {1, 2, 3, 4})', { f: '=STEYX({1, "a", 3, 4, 7}, {2, 5, 6, 9, 1})', expect: 3.021266088991138, why: 'pairs with a non-number are skipped' }, { f: '=STEYX({1, 2}, {1, 2})', expect: { error: '#DIV/0!' }, why: 'needs at least three points' }, { f: '=STEYX({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('COVARIANCE.P', 'COVARIANCE.P(array1, array2)', 'Returns the population covariance of two arrays.', ['=COVARIANCE.P({3, 2, 4, 5, 6}, {9, 7, 12, 15, 17})', '=COVARIANCE.P({1, 2, 3}, {3, 2, 1})', { f: '=COVARIANCE.P({1, "a", 3, 4}, {2, 5, 6, 9})', expect: 3.5555555555555554, why: 'pairs with a non-number are skipped' }, '=COVARIANCE.P(1, 2)', { f: '=COVARIANCE.P({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('COVARIANCE.S', 'COVARIANCE.S(array1, array2)', 'Returns the sample covariance of two arrays.', ['=COVARIANCE.S({2, 4, 8}, {5, 11, 12})', '=COVARIANCE.S({1, 2, 3}, {3, 2, 1})', { f: '=COVARIANCE.S({1, "a", 3, 4}, {2, 5, 6, 9})', expect: 5.333333333333333, why: 'pairs with a non-number are skipped' }, { f: '=COVARIANCE.S(1, 2)', expect: { error: '#DIV/0!' }, why: 'needs at least two pairs' }, { f: '=COVARIANCE.S({1, 2}, {1})', expect: { error: '#N/A' }, why: 'different sizes' }]),
  s('FORECAST', 'FORECAST(x, known_ys, known_xs)', 'Predicts a y value for x from a linear regression of known values.', ['=FORECAST(30, {6, 7, 9, 15, 21}, {20, 28, 31, 38, 40})', '=FORECAST(4, {2, 4, 6}, {1, 2, 3})', { f: '=FORECAST(0, {1, "a", 3, 4}, {2, 5, 6, 9})', expect: 0.21621621621621623, why: 'pairs with a non-number are skipped' }, { f: '=FORECAST(1, {1, 2}, {3, 3})', expect: { error: '#DIV/0!' }, why: 'all x equal' }, '=FORECAST("x", {1, 2}, {1, 2})']),
  s('FISHER', 'FISHER(x)', 'Returns the Fisher transformation of x (-1 < x < 1).', ['=FISHER(0.75)', '=FISHER(0)', '=FISHER(-0.5)', '=FISHER(1)', '=FISHER("x")']),
  s('FISHERINV', 'FISHERINV(y)', 'Returns the inverse of the Fisher transformation.', ['=FISHERINV(0.972955)', '=FISHERINV(0)', '=FISHERINV(-2)', '=FISHERINV(10)', '=FISHERINV("x")']),
  s('PERMUT', 'PERMUT(number, number_chosen)', 'Returns the number of permutations of number_chosen items from number items (truncated).', ['=PERMUT(100, 3)', '=PERMUT(3, 2)', '=PERMUT(5, 0)', '=PERMUT(5.9, 2.9)', { f: '=PERMUT(2, 3)', expect: { error: '#NUM!' }, why: 'number_chosen > number' }, { f: '=PERMUT(-1, 0)', expect: { error: '#NUM!' }, why: 'negative number' }, '=PERMUT("x", 1)']),
  s('PERMUTATIONA', 'PERMUTATIONA(number, number_chosen)', 'Returns the number of permutations with repetition, number^number_chosen.', ['=PERMUTATIONA(3, 2)', '=PERMUTATIONA(2, 2)', '=PERMUTATIONA(10, 0)', { f: '=PERMUTATIONA(4.9, 2)', expect: 16, why: 'number is truncated' }, { f: '=PERMUTATIONA(-1, 2)', expect: { error: '#NUM!' }, why: 'negative number' }, '=PERMUTATIONA("x", 1)']),
];
